version: '3'
services:
    honeypot_cowrie:
        build: ./cowrie
        image: cowrie
        restart: always
        ports:
        - "2222:2222"
        - "2223:2223"
        volumes:
            - "./cowrie/etc:/cowrie/cowrie-git/etc"
            - "./cowrie/var:/cowrie/cowrie-git/var"
        networks:
            honey_net:
                ipv4_address: 192.168.0.5


networks:
    honey_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
