version: '3'
services:
    honeypot_cowrie:
        build: ./cowrie
        image: cowrie
        restart: always
        ports:
        - "2222:2222"
        - "2223:2223"
        volumes:
            - "./cowrie/var:/cowrie/cowrie-git/var"
            - "./cowrie/etc:/cowrie/cowrie-git/etc"
        networks:
            honey_net:
                ipv4_address: 192.168.0.5

    honey_master:
        build: ./demohunter
        image: demohunter
        restart: always
        ports:
            - "8000:8000"
        networks:
            honey_net:
                ipv4_address: 192.168.0.10

# Instructions for setting an Agent:
# 1) Set an Agent on app and get the toke: ip on the dashboar has to bo only the IP
# 2) docker run -it -p 80:80 demohunter \
#       dh_run --dh-type honeypot --agent --master-addr http://<IP_Master>:8000 --agent-token <token_generate>

networks:
    honey_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
